// Code Generator Header File

#ifndef CODEGENERATOR_H
#define CODEGENERATOR_H


#include <string>
#include <iostream>
#include <fstream>


using namespace std;


// Class that will emit the machine code.
class CodeGenerator {
    private:
        // TODO: Add private members here.

    public:
        // Default ctor.
        CodeGenerator();

        // Class dtor to release resources.
        ~CodeGenerator();

        // TODO: OTHER PUBLIC FUNCTIONS.
};

#endif      /* CODEGENERATOR_H */

